### PR TITLE
gofmt -s

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by cored** [comment]
+1

**Comment by macat** [comment]
We are using go 1.6, no need for explicitly declaring the object types there. Closing this.

**Comment by shawnps** [comment]
@macat maybe I'm misunderstanding but isn't this removing the explicit declaration of `&deployment.Playbook`? I don't think it's related to using Go 1.6

**Comment by shawnps** [comment]
@macat in any case just for reference: https://golang.org/cmd/gofmt/#hdr-The_simplify_command

**Comment by macat** [comment]
Sorry, I misunderstood the PR. You are right, it is not related to Go 1.6.

**Pull request merged**
